# Genomic Biomarker Discovery for Breast Cancer Using Machine Learning and Cloud Computing

In [ ]:
import pandas as pd
import numpy as np

In [2]:
!rm /content/TCGA-BRCA.star_tpm.tsv.gz

rm: cannot remove '/content/TCGA-BRCA.star_tpm.tsv.gz': No such file or directory

In [3]:
!wget -O TCGA-BRCA.star_tpm.tsv.gz "https://gdc-hub.s3.us-east-1.amazonaws.com/download/TCGA-BRCA.star_tpm.tsv.gz"

--2026-05-12 19:20:24--  https://gdc-hub.s3.us-east-1.amazonaws.com/download/TCGA-BRCA.star_tpm.tsv.gz
Resolving gdc-hub.s3.us-east-1.amazonaws.com (gdc-hub.s3.us-east-1.amazonaws.com)... 54.231.159.2, 52.216.24.32, 52.217.81.56, ...
Connecting to gdc-hub.s3.us-east-1.amazonaws.com (gdc-hub.s3.us-east-1.amazonaws.com)|54.231.159.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 342300776 (326M) [text/tab-separated-values]
Saving to: ‘TCGA-BRCA.star_tpm.tsv.gz’

TCGA-BRCA.star_tpm. 100%[===================>] 326.44M  33.4MB/s    in 10s

2026-05-12 19:20:34 (31.5 MB/s) - ‘TCGA-BRCA.star_tpm.tsv.gz’ saved [342300776/342300776]

In [4]:
expr = pd.read_csv(
    "TCGA-BRCA.star_tpm.tsv.gz",
    sep="\t",
    compression='gzip'
)

expr.head()

,Ensembl_ID,TCGA-D8-A146-01A,TCGA-AQ-A0Y5-01A,TCGA-C8-A274-01A,TCGA-BH-A0BD-01A,TCGA-B6-A1KC-01B,TCGA-AC-A62V-01A,TCGA-AO-A0J5-01A,TCGA-BH-A0B1-01A,TCGA-A2-A0YM-01A,...,TCGA-E2-A1IG-01A,TCGA-E9-A1NA-01A,TCGA-D8-A1JP-01A,TCGA-AR-A252-01A,TCGA-D8-A1XL-01A,TCGA-BH-A0EI-01A,TCGA-E2-A1IO-01A,TCGA-E2-A15R-01A,TCGA-B6-A0IP-01A,TCGA-A1-A0SN-01A
0,ENSG00000000003.15,5.662037,3.703721,6.514515,4.784917,4.251984,3.536849,4.645690,6.021755,6.260931,...,4.825501,4.142806,4.960919,4.770121,5.276757,6.436490,6.184500,2.670931,6.834395,3.650719
1,ENSG00000000005.6,3.376096,0.463099,0.000000,2.328061,0.435415,0.736475,1.255622,0.392647,0.467593,...,0.134747,0.159500,0.079566,3.312418,0.000000,0.383608,0.755144,0.479644,0.526069,0.059909
2,ENSG00000000419.13,6.860140,7.086452,6.805072,6.443071,6.178436,6.823355,5.749910,6.977449,6.819887,...,6.382933,6.436308,6.994589,6.005000,7.382161,7.220846,6.868277,7.033110,6.384368,8.153019
3,ENSG00000000457.14,4.400552,4.051007,5.037264,4.374970,3.558464,2.108324,4.487107,4.021000,3.319560,...,3.891448,3.765057,4.946796,3.648707,3.664915,3.752192,4.093078,4.831796,4.368028,4.172247
4,ENSG00000000460.17,2.845169,2.426989,4.043248,4.162790,2.589548,2.277777,2.545178,3.372492,4.023974,...,2.557655,2.566596,3.746915,2.494160,3.104957,3.111549,2.538538,3.730901,3.311721,3.301075

In [5]:
!wget -O TCGA-BRCA.clinical.tsv.gz "https://gdc-hub.s3.us-east-1.amazonaws.com/download/TCGA-BRCA.clinical.tsv.gz"

--2026-05-12 19:20:56--  https://gdc-hub.s3.us-east-1.amazonaws.com/download/TCGA-BRCA.clinical.tsv.gz
Resolving gdc-hub.s3.us-east-1.amazonaws.com (gdc-hub.s3.us-east-1.amazonaws.com)... 52.216.41.74, 52.216.58.186, 54.231.138.26, ...
Connecting to gdc-hub.s3.us-east-1.amazonaws.com (gdc-hub.s3.us-east-1.amazonaws.com)|52.216.41.74|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 280146 (274K) [text/tab-separated-values]
Saving to: ‘TCGA-BRCA.clinical.tsv.gz’

TCGA-BRCA.clinical. 100%[===================>] 273.58K  1.48MB/s    in 0.2s

2026-05-12 19:20:57 (1.48 MB/s) - ‘TCGA-BRCA.clinical.tsv.gz’ saved [280146/280146]

In [6]:
clinical = pd.read_csv(
    "TCGA-BRCA.clinical.tsv.gz",
    sep="\t",
    compression='gzip'
)

clinical.head()

,sample,id,disease_type,case_id,submitter_id,primary_site,alcohol_history.exposures,race.demographic,gender.demographic,ethnicity.demographic,...,days_to_collection.samples,initial_weight.samples,preservation_method.samples,pathology_report_uuid.samples,oct_embedded.samples,specimen_type.samples,days_to_sample_procurement.samples,is_ffpe.samples,tissue_type.samples,annotations.samples
0,TCGA-BH-A0W3-01A,3c612e12-6de8-44fa-a095-805c45474821,Ductal and Lobular Neoplasms,3c612e12-6de8-44fa-a095-805c45474821,TCGA-BH-A0W3,Breast,Not Reported,white,female,not hispanic or latino,...,85.0,120.0,OCT,801A4E2F-E26E-424F-BF42-CD0D9CD62BCE,True,Solid Tissue,NaN,False,Tumor,NaN
1,TCGA-AR-A24V-01A,3cb06c7a-f2a8-448b-91a8-dd201bbf2ddd,Ductal and Lobular Neoplasms,3cb06c7a-f2a8-448b-91a8-dd201bbf2ddd,TCGA-AR-A24V,Breast,Not Reported,white,female,not hispanic or latino,...,1720.0,400.0,OCT,468CD293-C9F7-43C6-A40A-18FCDD22F6AA,True,Solid Tissue,NaN,False,Tumor,NaN
2,TCGA-E9-A1NE-01A,3d676bba-154b-4d22-ab59-d4d4da051b94,Ductal and Lobular Neoplasms,3d676bba-154b-4d22-ab59-d4d4da051b94,TCGA-E9-A1NE,Breast,Not Reported,white,female,not hispanic or latino,...,31.0,280.0,OCT,CF6E29A2-FAE6-45BB-B625-33877887A89E,True,Solid Tissue,NaN,False,Tumor,NaN
3,TCGA-E9-A1NE-11A,3d676bba-154b-4d22-ab59-d4d4da051b94,Ductal and Lobular Neoplasms,3d676bba-154b-4d22-ab59-d4d4da051b94,TCGA-E9-A1NE,Breast,Not Reported,white,female,not hispanic or latino,...,31.0,830.0,OCT,NaN,True,Solid Tissue,NaN,False,Normal,NaN
4,TCGA-AC-A8OQ-01A,dfaabd03-2d40-4422-b210-caf112ff4229,Ductal and Lobular Neoplasms,dfaabd03-2d40-4422-b210-caf112ff4229,TCGA-AC-A8OQ,Breast,Not Reported,black or african american,female,not hispanic or latino,...,742.0,100.0,Unknown,FFA6F9F3-71C1-4AF9-B9F7-0466550EBC90,False,Solid Tissue,NaN,False,Tumor,NaN

In [7]:
print(expr.shape)
expr.head()

(60660, 1227)

,Ensembl_ID,TCGA-D8-A146-01A,TCGA-AQ-A0Y5-01A,TCGA-C8-A274-01A,TCGA-BH-A0BD-01A,TCGA-B6-A1KC-01B,TCGA-AC-A62V-01A,TCGA-AO-A0J5-01A,TCGA-BH-A0B1-01A,TCGA-A2-A0YM-01A,...,TCGA-E2-A1IG-01A,TCGA-E9-A1NA-01A,TCGA-D8-A1JP-01A,TCGA-AR-A252-01A,TCGA-D8-A1XL-01A,TCGA-BH-A0EI-01A,TCGA-E2-A1IO-01A,TCGA-E2-A15R-01A,TCGA-B6-A0IP-01A,TCGA-A1-A0SN-01A
0,ENSG00000000003.15,5.662037,3.703721,6.514515,4.784917,4.251984,3.536849,4.645690,6.021755,6.260931,...,4.825501,4.142806,4.960919,4.770121,5.276757,6.436490,6.184500,2.670931,6.834395,3.650719
1,ENSG00000000005.6,3.376096,0.463099,0.000000,2.328061,0.435415,0.736475,1.255622,0.392647,0.467593,...,0.134747,0.159500,0.079566,3.312418,0.000000,0.383608,0.755144,0.479644,0.526069,0.059909
2,ENSG00000000419.13,6.860140,7.086452,6.805072,6.443071,6.178436,6.823355,5.749910,6.977449,6.819887,...,6.382933,6.436308,6.994589,6.005000,7.382161,7.220846,6.868277,7.033110,6.384368,8.153019
3,ENSG00000000457.14,4.400552,4.051007,5.037264,4.374970,3.558464,2.108324,4.487107,4.021000,3.319560,...,3.891448,3.765057,4.946796,3.648707,3.664915,3.752192,4.093078,4.831796,4.368028,4.172247
4,ENSG00000000460.17,2.845169,2.426989,4.043248,4.162790,2.589548,2.277777,2.545178,3.372492,4.023974,...,2.557655,2.566596,3.746915,2.494160,3.104957,3.111549,2.538538,3.730901,3.311721,3.301075

In [8]:
print(clinical.shape)
clinical.head()

(1255, 85)

,sample,id,disease_type,case_id,submitter_id,primary_site,alcohol_history.exposures,race.demographic,gender.demographic,ethnicity.demographic,...,days_to_collection.samples,initial_weight.samples,preservation_method.samples,pathology_report_uuid.samples,oct_embedded.samples,specimen_type.samples,days_to_sample_procurement.samples,is_ffpe.samples,tissue_type.samples,annotations.samples
0,TCGA-BH-A0W3-01A,3c612e12-6de8-44fa-a095-805c45474821,Ductal and Lobular Neoplasms,3c612e12-6de8-44fa-a095-805c45474821,TCGA-BH-A0W3,Breast,Not Reported,white,female,not hispanic or latino,...,85.0,120.0,OCT,801A4E2F-E26E-424F-BF42-CD0D9CD62BCE,True,Solid Tissue,NaN,False,Tumor,NaN
1,TCGA-AR-A24V-01A,3cb06c7a-f2a8-448b-91a8-dd201bbf2ddd,Ductal and Lobular Neoplasms,3cb06c7a-f2a8-448b-91a8-dd201bbf2ddd,TCGA-AR-A24V,Breast,Not Reported,white,female,not hispanic or latino,...,1720.0,400.0,OCT,468CD293-C9F7-43C6-A40A-18FCDD22F6AA,True,Solid Tissue,NaN,False,Tumor,NaN
2,TCGA-E9-A1NE-01A,3d676bba-154b-4d22-ab59-d4d4da051b94,Ductal and Lobular Neoplasms,3d676bba-154b-4d22-ab59-d4d4da051b94,TCGA-E9-A1NE,Breast,Not Reported,white,female,not hispanic or latino,...,31.0,280.0,OCT,CF6E29A2-FAE6-45BB-B625-33877887A89E,True,Solid Tissue,NaN,False,Tumor,NaN
3,TCGA-E9-A1NE-11A,3d676bba-154b-4d22-ab59-d4d4da051b94,Ductal and Lobular Neoplasms,3d676bba-154b-4d22-ab59-d4d4da051b94,TCGA-E9-A1NE,Breast,Not Reported,white,female,not hispanic or latino,...,31.0,830.0,OCT,NaN,True,Solid Tissue,NaN,False,Normal,NaN
4,TCGA-AC-A8OQ-01A,dfaabd03-2d40-4422-b210-caf112ff4229,Ductal and Lobular Neoplasms,dfaabd03-2d40-4422-b210-caf112ff4229,TCGA-AC-A8OQ,Breast,Not Reported,black or african american,female,not hispanic or latino,...,742.0,100.0,Unknown,FFA6F9F3-71C1-4AF9-B9F7-0466550EBC90,False,Solid Tissue,NaN,False,Tumor,NaN

In [9]:
expr = expr.set_index(expr.columns[0])

In [10]:
expr.head()

,TCGA-D8-A146-01A,TCGA-AQ-A0Y5-01A,TCGA-C8-A274-01A,TCGA-BH-A0BD-01A,TCGA-B6-A1KC-01B,TCGA-AC-A62V-01A,TCGA-AO-A0J5-01A,TCGA-BH-A0B1-01A,TCGA-A2-A0YM-01A,TCGA-AO-A03N-01B,...,TCGA-E2-A1IG-01A,TCGA-E9-A1NA-01A,TCGA-D8-A1JP-01A,TCGA-AR-A252-01A,TCGA-D8-A1XL-01A,TCGA-BH-A0EI-01A,TCGA-E2-A1IO-01A,TCGA-E2-A15R-01A,TCGA-B6-A0IP-01A,TCGA-A1-A0SN-01A
Ensembl_ID,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.15,5.662037,3.703721,6.514515,4.784917,4.251984,3.536849,4.645690,6.021755,6.260931,3.613025,...,4.825501,4.142806,4.960919,4.770121,5.276757,6.436490,6.184500,2.670931,6.834395,3.650719
ENSG00000000005.6,3.376096,0.463099,0.000000,2.328061,0.435415,0.736475,1.255622,0.392647,0.467593,0.000000,...,0.134747,0.159500,0.079566,3.312418,0.000000,0.383608,0.755144,0.479644,0.526069,0.059909
ENSG00000000419.13,6.860140,7.086452,6.805072,6.443071,6.178436,6.823355,5.749910,6.977449,6.819887,6.079559,...,6.382933,6.436308,6.994589,6.005000,7.382161,7.220846,6.868277,7.033110,6.384368,8.153019
ENSG00000000457.14,4.400552,4.051007,5.037264,4.374970,3.558464,2.108324,4.487107,4.021000,3.319560,2.287502,...,3.891448,3.765057,4.946796,3.648707,3.664915,3.752192,4.093078,4.831796,4.368028,4.172247
ENSG00000000460.17,2.845169,2.426989,4.043248,4.162790,2.589548,2.277777,2.545178,3.372492,4.023974,1.753177,...,2.557655,2.566596,3.746915,2.494160,3.104957,3.111549,2.538538,3.730901,3.311721,3.301075

In [11]:
expr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60660 entries, ENSG00000000003.15 to ENSG00000288675.1
Columns: 1226 entries, TCGA-D8-A146-01A to TCGA-A1-A0SN-01A
dtypes: float64(1226)
memory usage: 567.9+ MB

In [12]:
clinical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1255 entries, 0 to 1254
Data columns (total 85 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   sample                                                     1255 non-null   object
 1   id                                                         1255 non-null   object
 2   disease_type                                               1255 non-null   object
 3   case_id                                                    1255 non-null   object
 4   submitter_id                                               1255 non-null   object
 5   primary_site                                               1255 non-null   object
 6   alcohol_history.exposures                                  1254 non-null   object
 7   race.demographic                                           1254 non-null   object
 8   gender.demographic                                         1254 non-null   object
 9   ethnicity.demographic                                      1254 non-null   object
 10  vital_status.demographic                                   1254 non-null   object
 11  age_at_index.demographic                                   1254 non-null   float64
 12  days_to_birth.demographic                                  1238 non-null   float64
 13  year_of_birth.demographic                                  1251 non-null   float64
 14  year_of_death.demographic                                  147 non-null    float64
 15  primary_site.project                                       1255 non-null   object
 16  project_id.project                                         1255 non-null   object
 17  disease_type.project                                       1255 non-null   object
 18  name.project                                               1255 non-null   object
 19  name.program.project                                       1255 non-null   object
 20  tissue_source_site_id.tissue_source_site                   1255 non-null   object
 21  code.tissue_source_site                                    1255 non-null   object
 22  name.tissue_source_site                                    1255 non-null   object
 23  project.tissue_source_site                                 1255 non-null   object
 24  bcr_id.tissue_source_site                                  1255 non-null   object
 25  days_to_death.demographic                                  203 non-null    float64
 26  entity_submitter_id.annotations                            33 non-null     object
 27  notes.annotations                                          33 non-null     object
 28  submitter_id.annotations                                   33 non-null     object
 29  classification.annotations                                 33 non-null     object
 30  entity_id.annotations                                      33 non-null     object
 31  created_datetime.annotations                               33 non-null     object
 32  annotation_id.annotations                                  33 non-null     object
 33  entity_type.annotations                                    33 non-null     object
 34  updated_datetime.annotations                               33 non-null     object
 35  case_id.annotations                                        33 non-null     object
 36  state.annotations                                          33 non-null     object
 37  category.annotations                                       33 non-null     object
 38  status.annotations                                         33 non-null     object
 39  case_submitter_id.annotations                              33 non-null     object
 40  synchronous_malignancy.diagnoses                           1254 non-null   object
 41  ajcc_pathologic_stage.diagnoses                            1242 non-null   object
 42  days_to_diagnosis.diagnoses                                1254 non-null   float64
 43  last_known_disease_status.diagnoses                        1254 non-null   object
 44  tissue_or_organ_of_origin.diagnoses                        1254 non-null   object
 45  days_to_last_follow_up.diagnoses                           1107 non-null   float64
 46  age_at_diagnosis.diagnoses                                 1238 non-null   float64
 47  primary_diagnosis.diagnoses                                1254 non-null   object
 48  prior_malignancy.diagnoses                                 1254 non-null   object
 49  year_of_diagnosis.diagnoses                                1252 non-null   float64
 50  prior_treatment.diagnoses                                  1254 non-null   object
 51  ajcc_staging_system_edition.diagnoses                      1080 non-null   object
 52  ajcc_pathologic_t.diagnoses                                1254 non-null   object
 53  morphology.diagnoses                                       1254 non-null   object
 54  ajcc_pathologic_n.diagnoses                                1254 non-null   object
 55  ajcc_pathologic_m.diagnoses                                1254 non-null   object
 56  classification_of_tumor.diagnoses                          1254 non-null   object
 57  icd_10_code.diagnoses                                      1254 non-null   object
 58  site_of_resection_or_biopsy.diagnoses                      1254 non-null   object
 59  tumor_grade.diagnoses                                      1254 non-null   object
 60  progression_or_recurrence.diagnoses                        1254 non-null   object
 61  age_at_earliest_diagnosis.diagnoses.xena_derived           1238 non-null   float64
 62  age_at_earliest_diagnosis_in_years.diagnoses.xena_derived  1238 non-null   float64
 63  treatment_id.treatments.diagnoses                          1254 non-null   object
 64  submitter_id.treatments.diagnoses                          1254 non-null   object
 65  treatment_type.treatments.diagnoses                        1254 non-null   object
 66  treatment_or_therapy.treatments.diagnoses                  1254 non-null   object
 67  created_datetime.treatments.diagnoses                      1254 non-null   object
 68  updated_datetime.treatments.diagnoses                      1254 non-null   object
 69  state.treatments.diagnoses                                 1254 non-null   object
 70  sample_type_id.samples                                     1255 non-null   int64
 71  tumor_descriptor.samples                                   1255 non-null   object
 72  sample_id.samples                                          1255 non-null   object
 73  sample_type.samples                                        1255 non-null   object
 74  composition.samples                                        1254 non-null   object
 75  days_to_collection.samples                                 1253 non-null   float64
 76  initial_weight.samples                                     1240 non-null   float64
 77  preservation_method.samples                                1255 non-null   object
 78  pathology_report_uuid.samples                              1118 non-null   object
 79  oct_embedded.samples                                       1255 non-null   bool
 80  specimen_type.samples                                      1255 non-null   object
 81  days_to_sample_procurement.samples                         4 non-null      float64
 82  is_ffpe.samples                                            1255 non-null   bool
 83  tissue_type.samples                                        1255 non-null   object
 84  annotations.samples                                        1 non-null      object
dtypes: bool(2), float64(14), int64(1), object(68)
memory usage: 816.4+ KB

In [13]:
expr_t = expr.T

In [14]:
expr_t.shape

(1226, 60660)

In [15]:
clinical['sample_type.samples'].value_counts()

sample_type.samples
Primary Tumor          1111
Solid Tissue Normal     137
Metastatic                7
Name: count, dtype: int64

In [16]:
expr_t.index[:5]

Index(['TCGA-D8-A146-01A', 'TCGA-AQ-A0Y5-01A', 'TCGA-C8-A274-01A',
       'TCGA-BH-A0BD-01A', 'TCGA-B6-A1KC-01B'],
      dtype='object')

In [17]:
clinical['submitter_id'].head()

0    TCGA-BH-A0W3
1    TCGA-AR-A24V
2    TCGA-E9-A1NE
3    TCGA-E9-A1NE
4    TCGA-AC-A8OQ
Name: submitter_id, dtype: object

In [20]:
expr_t['patient_id'] = expr_t.index.str.slice(0,12)

In [21]:
expr_t['patient_id'].head()

TCGA-D8-A146-01A    TCGA-D8-A146
TCGA-AQ-A0Y5-01A    TCGA-AQ-A0Y5
TCGA-C8-A274-01A    TCGA-C8-A274
TCGA-BH-A0BD-01A    TCGA-BH-A0BD
TCGA-B6-A1KC-01B    TCGA-B6-A1KC
Name: patient_id, dtype: object

In [22]:
merged = expr_t.merge(
    clinical,
    left_on='patient_id',
    right_on='submitter_id'
)

In [23]:
merged.shape

(1529, 60746)

In [24]:
filtered = merged[
    merged['sample_type.samples'].isin([
        'Primary Tumor',
        'Solid Tissue Normal'
    ])
]

In [25]:
filtered['label'] = filtered['sample_type.samples'].map({
    'Primary Tumor': 1,
    'Solid Tissue Normal': 0
})

/tmp/ipykernel_9354/442765336.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['label'] = filtered['sample_type.samples'].map({

In [26]:
filtered['label'].value_counts()

label
1    1254
0     258
Name: count, dtype: int64

Removing the duplicates by using labels directly from expression sample IDs.

In [27]:
merged['patient_id'].duplicated().sum()

np.int64(434)

In [28]:
merged['patient_id'].value_counts().head()

patient_id
TCGA-A7-A0DC    9
TCGA-BH-A18V    9
TCGA-A7-A13G    9
TCGA-A7-A0DB    9
TCGA-BH-A1FE    9
Name: count, dtype: int64

In [29]:
expr_t['sample_code'] = expr_t.index.str.slice(13,15)

In [30]:
expr_t['sample_code'].value_counts()

sample_code
01    1106
11     113
06       7
Name: count, dtype: int64

In [31]:
expr_t = expr_t[
    expr_t['sample_code'].isin(['01', '11'])
]

In [33]:
expr_t['label'] = expr_t['sample_code'].map({
    '01': 1,
    '11': 0
})

In [34]:
expr_t['label'].value_counts()

label
1    1106
0     113
Name: count, dtype: int64

In [37]:
expr_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1219 entries, TCGA-D8-A146-01A to TCGA-A1-A0SN-01A
Columns: 60663 entries, ENSG00000000003.15 to label
dtypes: float64(60660), int64(1), object(2)
memory usage: 564.2+ MB

In [39]:
final_dataset = expr_t.drop(columns=['sample_code'])

final_dataset.to_csv(
    "brca_clean_expression_dataset.csv"
)

In [40]:
from google.colab import files

files.download("brca_clean_expression_dataset.csv")